---
- name: Deploy files using a jinja2 template
  hosts: all
  become: true

  tasks:
    - name: Deploy message of the day template
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
