---
- hosts: all
  become: yes
  become_user: root
  vars_files:
    - vault/main.yml

  roles:
    - wazuh-agent
  vars:
    wazuh_managers:
      - address: 192.168.0.109
        port: 1514
        protocol: tcp
        max_retries: 5
        retry_interval: 5