---
- name: Instalacja agenta zabbix
  gather_facts: yes
  hosts: all

  tasks:
    - name: Instalacja zabbixa na dystrybucji RedHat
      include_tasks: zabbixAgentRedHat.yaml
      when: ansible_facts['os_family'] == "RedHat"

    - name: Instalacja zabbixa na dystrybucji Debian
      include_tasks: zabbixAgentDebian.yaml  
      when: >
        ( ansible_distribution == "Debian" and 
        ansible_distribution_version is version('8', '>') )

    - name: Instalacja zabbixa na systemie Windows
      include_tasks: zabbixAgentWindows.yaml
      when: ansible_facts['os_family'] == "Windows"
