---
- name: Instalacja agenta zabbix
  hosts: all
  become: true

  tasks:
    - name: Instalacja zabbixa na dystrybucji RedHat
      include_tasks: zabbixAgentRedHat.yaml
      when: ansible_facts['os_family'] == "RedHat"

    - name: Instalacja zabbixa na dystrybucji Debian
      include_tasks: zabbixAgentDebian.yaml  
      when: >
        ( ansible_distribution == "Debian" and 
        ansible_distribution_version is version('8', '>') )
