- name: Aktualizacja pakietów
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Instalacja pakietów
  apt:
    name: 
      - git
      - vim
      - htop
    state: present
    update_cache: yes
