- name: Aktualizacja pakietów
  yum:
    name: '*'
    update_cache: yes
    state: latest

- name: install epel-release
  dnf:
    name: epel-release
    state: present

- name: Instalacja pakietów
  dnf:
    name: 
      - git
      - vim
      - htop
      - curl
    state: present

- name: check for updates (yum)
  yum: list=updates update_cache=true
  register: yumoutput

- debug:
    msg: "{{ yumoutput.results | map(attribute='name') | list }}"

- name: check for updates (yum)
  yum: list=updates update_cache=true
  register: yumoutput

- debug:
    msg: "{{ yumoutput.results | map(attribute='name') | list }}"

- name: Remove dependencies that are no longer required
  ansible.builtin.dnf:
    autoremove: yes