- name: Aktualizacja pakietów
  yum:
    name: '*'
    state: latest

- name: Instalacja pakietów
  dnf:
    name: 
      - git
      - vim
      - htop
      - curl
    state: present

- name: Remove dependencies that are no longer required
  ansible.builtin.dnf:
    autoremove: yes