- name: Aktualizacja pakietów
  yum:
    name: '*'
    update_cache: yes
    state: latest

- name: install epel-release
  dnf:
    name: epel-release
    state: present

- name: Instalacja pakietów
  dnf:
    name: 
      - git
      - vim
      - htop
      - curl
    state: present

- name: List updated packages
  shell: rpm -qa --last | sed -E 's/..[0-9]{2}:[0-9]{2}:[0-9]{2}//' | grep "$(date +%d\ %b\ %Y)" | cut -f 1 -d " "
  register: result
  args:
    warn: no

- name: Updates packages
  debug: msg="{{ result.stdout_lines }}"

- name: Remove dependencies that are no longer required
  ansible.builtin.dnf:
    autoremove: yes