- name: Instalacja Chocolatey
  win_chocolatey:
    name: chocolatey
    state: present

- name: Instalacja Zabbixa
  win_chocolatey:
    name: zabbix-agent.install
    version: '{{ zabbixAgentWindows_version }}'
    state: upgrade

- name: Pobranie konfiguracji
  win_template:
    src: zabbix_win.j2
    dest: "{{ zabbix_conf_path }}"
  notify: restart zabbix-agent_windows

- name: Install python
  win_chocolatey:
    name: python
    version: '3.10.5'
    state: present

- name: Ustaw status instalacji na 1
  set_fact:
    install: '1'