---
- block:
  - name: Sprawdz wersje zabbixa
    command: "{{ zabbix_daemon_path }}{{ zabbix_daemon }} -V"
    changed_when: false
    check_mode: false
    register: wersja_zabbixa

  - name: Stwórz zmienną z wersją
    set_fact:
      wersja_zabbixa: "{{ wersja_zabbixa.stdout.split()[3] }}"

  - name: Wyświetl zainstalowaną wersję
    debug:
      msg: "{{ wersja_zabbixa }}"

  - name: Wyświetl wersję, jaką chcesz zainstalować
    debug:
      msg: "{{ zabbixAgentDebian_versionMinor }}"

  rescue: 
    - name: Przechodzę do rescue
      debug:
        msg: "Brak zainstalowanego zabbixa, przechodzę do instalacji"

    - include_tasks: agent-Debian.yml