---
- block:
  - name: Sprawdz wersje zabbixa
    command: "{{ zabbix_daemon_path }}{{ zabbix_daemon }} -V"
    changed_when: false
    check_mode: false
    register: wersja_zabbixa

  - name: Create wersja_zabixa variable.
    set_fact:
      wersja_zabbixa: "{{ wersja_zabbixa.stdout.split()[3] }}"

  rescue: 
    - name: Część rescue
      debug:
        msg: "Brak zainstalowanego zabbixa, przechodzę do instalacji"

    - include_tasks: agent-RedHat.yml
