- name: Aktualizacja pakietów
  yum:
    update_cache: yes

- name: Instalacja pakietu z repo
  yum:
    name: https://repo.zabbix.com/zabbix/{{ zabbixAgentRedHat_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-agent-{{ zabbixAgentRedHat_versionMinor }}.el{{ ansible_distribution_major_version }}.x86_64.rpm
    state: present
    disable_gpg_check: yes
    validate_certs: no

- name: Sprawdz i pobierz aktualizacje dla zabbix-agenta
  yum:
    name: zabbix-agent
    state: latest
    download_only: yes
  notify: stop zabbix-agent

- name: Zainstaluj aktualizacje dla zabbix-agenta
  yum:
    name: zabbix-agent
    state: latest
  notify: start zabbix-agent  

- name: Pobranie konfiguracji .j2
  template:
    src: zabbix.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: "0644"
  notify: start zabbix-agent

- name: Otwieranie portów 
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: true
  loop: "{{ open_ports }}"
  notify: przeladuj firewalla_redhat

- name: install pip
  dnf:
    name: python3-pip
    state: present

- name: install and upgrade pip module
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
      
- name: install zabbix-api
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pip:
    name: zabbix-api
    state: present

- name: Create new host
  community.zabbix.zabbix_host:
    server_url: "http://192.168.0.10/zabbix"
    login_user: "{{ add_host_zabbix_login }}"
    login_password: "{{ add_host_zabbix_password }}"
    host_name: "{{ ansible_hostname }}"
    visible_name: "{{ ansible_hostname }}"
    host_groups: Zabbix servers
    status: enabled
    state: present
    inventory_mode: manual
    link_templates:
      - Linux by Zabbix agent
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: ""
        port: "10051"