- block:
  - name: Porównanie wersji zainstalowanej oraz instalowanej
    debug:
      msg: "Chcesz zainstalować nizszą wersje niz aktualnie uzywasz, reszta kroktów będzie pominięta!"
  when: zabbixAgentWindows_version < zabbix_version_check['win_file_version']['product_version'] 

- block:
  - name: Instalacja Chocolatey
    win_chocolatey:
      name: chocolatey
      state: present

  - name: Instalacja Zabbixa
    win_chocolatey:
      name: zabbix-agent.install
      version: '{{ zabbixAgentWindows_version }}'
      state: upgrade

  - name: Pobranie konfiguracji
    win_template:
      src: zabbix_win.j2
      dest: "{{ zabbix_conf_path }}"
    notify: restart zabbix-agent_windows